### ISSUE TITLE
Day 2: Grades Dictionary contains duplicate key

### ISSUE THREAD

**Issue by annkatrinkuessner** [zotroneneis/magical_universe#7]
Hey! 

In  the blog post of Day  2 you give examples for static methods, however the dictionary used in the passed method contains the duplicate key "P":
```
grades = {
               'O': True,
                'Ordinary': True,
                'P': True,
                'Passed': True,
                'A': True,
                'Acceptable': True,
                'P': False,
                'Poor': False,
                'H': False,
                'Horrible': False,
                }
```

Don't think it's utterly important as the method does not show up in the code for the day. In addition  to that the second occurence should overwrite the first so it still returns a value when calling the method.

**Comment by zotroneneis** [comment]
Yes, I fixed that in the main version a few days ago. I will fix the individual files ASAP!
