### ISSUE TITLE
Day 8: Wrong parameter type

### ISSUE THREAD

**Issue by thatlittleboy** [zotroneneis/magical_universe#8]
https://github.com/zotroneneis/magical_universe/blob/d275570cd9b67d4fa7f02bfcd4d2d8ce4811ef91/code_per_day/day_8.py#L92

It should read 

`return cls('The Mocking Knight', 1401, 'male', 1492, 'House of Courage') `

I believe, since the `Ghost` class is expecting an Int `year_of_death`.

**Comment by zotroneneis** [comment]
Absolutely, thanks for pointing it out! 👍
